import type { Metadata } from "next";
import { Inter, Poppins,Noto_Serif_Old_Uyghur } from "next/font/google";
import "./globals.css";

const fonts_poppins = Poppins({ subsets: ["latin"],weight:["100", "200", "300", "400", "500", "600"] });
export const fonts_old_uyghur  = Noto_Serif_Old_Uyghur({weight:["400"],subsets:["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fonts_poppins.className}>{children}</body>
    </html>
  );
}
